### ISSUE TITLE
/python/ and /autoindex/

### ISSUE THREAD

**Issue by snemoto-42** [ichinose9372/42-webserv#82]
・実行環境によって/python/の結果がブラウザに表示されない
（校舎mac:ok/mypc:ng、pythonの実行環境の問題、pythonなのかpython3なのか）
・統一された環境でレビューしてもらうにはdockerが必要か

**Comment by snemoto-42** [comment]
・.cnfファイルにてlocation /python/のcgi_path /usr/bin/python;に修正
（校舎macにはpython3がインストールされていない）

**Comment by snemoto-42** [comment]
interpreterの指定は意味なし?
→webservのexecveで実行
→venvでinterpreterを指定できる?

pathではなくdirecvoryを指定

**Comment by snemoto-42** [comment]
課題

Traceback (most recent call last): File "./docs/autoindex/app.py", line 4, in from flask import Flask, render_template File "/Users/snemoto/42/42-webserv/env/lib/python3.9/site-packages/flask/init.py", line 46 def getattr(name: str) -> t.Any: ^ SyntaxError: invalid syntax

１execve()環境変数の問題？
https://www.twilio.com/ja/blog/environment-variables-python-jp

２シバンの問題？
（実行可能）/usr/bin/env python
（実行不可）/usr/bin/env python3
（実行不可）/usr/bin/env python3.9

**Comment by snemoto-42** [comment]
TODO
・/autoindex/のgetcwd()を修正、絶対パスを指定して/docs/傘下のファイルを表示
・autoindex.htmlの<td>{{ path }}</td>を修正
・flaskで/python/のルーティング

**Comment by snemoto-42** [comment]
バグは解消されたのでクローズ
